name: Deploy develop branch to GitHub Pages
on:
  push:
    branches: [ develop ]

jobs:
  deploy-flutter-gh-pages:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      MAPBOX_ACCESS_TOKEN: 'pk.eyJ1IjoieXNhdmFyeSIsImEiOiJja3Mxa3VmcWIwajQ2MzBxbW11OHprYWhzIn0.AGc4Z1JSipyl6WApGZkJhQ'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java 8
        uses: actions/setup-java@v1
        with:
          java-version: '8.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
          flutter-version: '2.4.x'

      - name: Deploy to GitHub Pages
        uses: erickzanardo/flutter-gh-pages@v6
        with:
          customArgs: >-
            --base-href=/winds-mobi-client-flutter/
            --dart-define=MAPBOX_ACCESS_TOKEN=${{ env.MAPBOX_ACCESS_TOKEN }}
            --source-maps
