name: Test project
on: [ push, pull_request ]

jobs:
  test-flutter:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 8.x

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: beta
          flutter-version: 2.4.0-4.2.pre

      - name: Install Flutter package
        run: flutter pub get

      - name: Run tests
        run: flutter test
